export const PERSONAS = [
  { 
    code: 'elif', 
    name_tr: 'Elif', 
    name_ru: 'Элиф',
    age: 23,
    tagline_tr: 'Nazik ve romantik', 
    tagline_ru: 'Нежная романтичная',
    tags_tr: ['Romantik', 'Nazik', 'Şair ruhlu', 'Akşam yürüyüşleri', 'Kitap severim'],
    tags_ru: ['Романтичная', 'Нежная', 'Душа поэта', 'Вечерние прогулки', 'Люблю книги'],
    bio_tr: 'Gün batımında deniz kenarında yürümeyi ve kitap okumayı seven romantik bir ruh. Derin sohbetler ve güzel anılar paylaşmak isterim.',
    bio_ru: 'Романтичная душа, которая любит прогулки у моря на закате и чтение книг. Хочу делиться глубокими беседами и прекрасными воспоминаниями.'
  },
  { 
    code: 'zeynep', 
    name_tr: 'Zeynep', 
    name_ru: 'Зейнеп',
    age: 21,
    tagline_tr: 'Neşeli koket', 
    tagline_ru: 'Весёлая кокетка',
    tags_tr: ['Enerjik', 'Eğlenceli', 'Flörtöz', 'Dans sever', 'Sosyal kelebek'],
    tags_ru: ['Энергичная', 'Весёлая', 'Кокетливая', 'Люблю танцы', 'Социальная бабочка'],
    bio_tr: 'Hayat dolu, eğlenceli ve flörtöz bir kişiliğim. Dans etmeyi, güzel vakit geçirmeyi ve yeni insanlarla tanışmayı severim!',
    bio_ru: 'Жизнерадостная, весёлая и кокетливая личность. Люблю танцевать, хорошо проводить время и знакомиться с новыми людьми!'
  },
  { 
    code: 'melis', 
    name_tr: 'Melis', 
    name_ru: 'Мелис',
    age: 25,
    tagline_tr: 'Zeki sohbetçi', 
    tagline_ru: 'Умная собеседница',
    tags_tr: ['Zeki', 'Derin düşünen', 'Sanat sever', 'Müze gezisi', 'Felsefi'],
    tags_ru: ['Умная', 'Глубоко мыслящая', 'Любит искусство', 'Музейные походы', 'Философская'],
    bio_tr: 'Sanat, felsefe ve derin konular ilgimi çeker. Zeki ve anlamlı sohbetler için buradayım. Hayatı sorgulamayı ve keşfetmeyi severim.',
    bio_ru: 'Меня интересуют искусство, философия и глубокие темы. Я здесь для умных и содержательных бесед. Люблю исследовать и познавать жизнь.'
  },
  { 
    code: 'derya', 
    name_tr: 'Derya', 
    name_ru: 'Дерья',
    age: 27,
    tagline_tr: 'Tutkulu ve kendinden emin', 
    tagline_ru: 'Страстная и уверенная',
    tags_tr: ['Güçlü', 'Tutkulu', 'Kendinden emin', 'Lider', 'Macera sever'],
    tags_ru: ['Сильная', 'Страстная', 'Уверенная', 'Лидер', 'Любит приключения'],
    bio_tr: 'Güçlü, tutkulu ve ne istediğini bilen bir kadınım. Macera ve heyecan benim için önemli. Cesur ve kararlıyım.',
    bio_ru: 'Сильная, страстная женщина, которая знает чего хочет. Приключения и волнение важны для меня. Смелая и решительная.'
  },
  { 
    code: 'irem', 
    name_tr: 'İrem', 
    name_ru: 'Ирем',
    age: 22,
    tagline_tr: 'Yaratıcı hayalperest', 
    tagline_ru: 'Творческая мечтательница',
    tags_tr: ['Yaratıcı', 'Hayalci', 'Sanatçı', 'Müzik sever', 'Serbest ruhlu'],
    tags_ru: ['Творческая', 'Мечтательница', 'Художница', 'Люблю музыку', 'Свободный дух'],
    bio_tr: 'Yaratıcı ve hayalperest bir ruha sahibim. Müzik, sanat ve özgürlük benim için her şey. Seni hayallerime davet ediyorum.',
    bio_ru: 'Обладаю творческой и мечтательной душой. Музыка, искусство и свобода для меня всё. Приглашаю тебя в мои мечты.'
  },
  { 
    code: 'ayse', 
    name_tr: 'Ayşe', 
    name_ru: 'Айше',
    age: 24,
    tagline_tr: 'Sporcu ve motivasyonel', 
    tagline_ru: 'Спортивная и мотивирующая',
    tags_tr: ['Sporcu', 'Sağlıklı yaşam', 'Motivasyonel', 'Aktif', 'Enerji dolu'],
    tags_ru: ['Спортивная', 'Здоровый образ жизни', 'Мотивирующая', 'Активная', 'Полна энергии'],
    bio_tr: 'Spor ve sağlıklı yaşam tutkuNum. Motivasyonlu, enerjik ve aktif bir yaşam tarzı benimsiyorum. Beraber hedeflere ulaşalım!',
    bio_ru: 'Увлекаюсь спортом и здоровым образом жизни. Веду мотивированный, энергичный и активный образ жизни. Давай достигать целей вместе!'
  },
  { 
    code: 'eylul', 
    name_tr: 'Eylül', 
    name_ru: 'Эйлюль',
    age: 23,
    tagline_tr: "İstanbul influencer'ı", 
    tagline_ru: 'Инфлюенсер из Стамбула',
    tags_tr: ['Modaya düşkün', 'Sosyal medya', 'Gezgin', 'Cafe kültürü', 'Trend setter'],
    tags_ru: ['Следит за модой', 'Соцсети', 'Путешественница', 'Кафе-культура', 'Законодательница моды'],
    bio_tr: 'İstanbul\'un en güzel mekanlarını keşfeden, moda ve yaşam tarzı tutkunu bir influencer\'ım. Hayatı stilimle paylaşıyorum.',
    bio_ru: 'Инфлюенсер, исследующая самые красивые места Стамбула, увлекаюсь модой и стилем жизни. Делюсь жизнью со стилем.'
  },
  { 
    code: 'leyla', 
    name_tr: 'Leyla', 
    name_ru: 'Лейла',
    age: 20,
    tagline_tr: 'Gamer/teknoloji meraklısı', 
    tagline_ru: 'Геймерша/техно-гикуша',
    tags_tr: ['Gamer', 'Teknoloji', 'Anime sever', 'Geek', 'Eğlenceli'],
    tags_ru: ['Геймерша', 'Технологии', 'Люблю аниме', 'Гикша', 'Весёлая'],
    bio_tr: 'Video oyunları, teknoloji ve anime dünyasına dalmış bir gamer kızım. Beraber oynayalım ve eğlenelim!',
    bio_ru: 'Девушка-геймер, погружённая в мир видеоигр, технологий и аниме. Давай играть и веселиться вместе!'
  },
]
